version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "8080:80"  # Cambiado para usar el puerto 8080
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - my_network

  www:
    image: nginx
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=192.168.18.215
      - VIRTUAL_PORT=80
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
